### ISSUE TITLE
Can't send large folders (`no space left on device`)

### ISSUE THREAD

**Issue by raingloom** [Jacalz/rymdport#93]
### Checklist

- [X] I have searched the [issue tracker](https://github.com/Jacalz/rymdport/issues) for open issues that relate to the same problem, before opening a new one.
- [X] This issue only relates to a single bug. I will open new issues for any other problems.

### Description

Here is the error:
```
2023/07/27 14:49:43 Fyne error:  Error on sending directory
2023/07/27 14:49:43   Cause: write /tmp/wormhole-william-dir1332995391: no space left on device
2023/07/27 14:49:43   At: github.com/Jacalz/rymdport/v3/internal/transport/bridge/send.go:190
```

I suspect that this is because similar to the Python version you are constructing the zip file in /tmp instead of doing the proper thing and streaming it.  Otherwise you are doubling disk usage for sending a file, which is pretty bad when the file or directory is several gigabytes in size.

It's likely running out of memory because Flatpak mounts /tmp as a tmpfs instead of backing it by disk.

### Steps to Reproduce

1. Find a large folder or create one, it should be bigger than the amount of free RAM or storage you have.
2. Try sending it.

### Rymdport version

3.4.0 (Flatpak)

### Operating System

Linux

### Operating System Version

guix 182be30

**Comment by Jacalz** [comment]
I appreciate the report but I don't think there is anything that I can do about this at this point in time.

The zip-creation happens inside the [workhole-william](https://github.com/psanford/wormhole-william) dependency and is not a bug in this project. However, I also believe that it is an inherent weakness of the wormhole protocol that you need to know the size of the file (the zip-file in the case of directory transfers) before you send it.

I 100% agree with you that it would be a lot better to stream the zip-file but we need to know the size before starting the transfer (I think) and I doubt that it will be possible to use streaming in that case. However, I will look into this to see if there is anything that can be done about it.

FYI: It is also worth noting that the Python version of wormhole is the reference implementation of the protocol. If it doesn't work there then it probably wouldn't work in the Go implementation either.

**Comment by Jacalz** [comment]
It definitely is problematic with the Flatpak. Will have to try and see if there is any way to work around the issue

**Comment by raingloom** [comment]
Thanks, in the meantime I found that this error was coming from core.

I started working on converting the Python reference implementation to
simply use a streaming zip library.
Especially with my use case of sending a bunch of JPEGs there is zero
point in compressing the folder, since each file is already compressed,
so I can just create the stream twice.  Once to find the length and the
second time to actually send it.

An alternative I'm considering is to just simply give an upper bound
based on the combined size of the files, but I'll have to check the
specs to make sure that sending a smaller file is allowed.

**Comment by Jacalz** [comment]
That sounds like a good idea. I had some similar thoughts about how this might be solved. It sounds like we are on the same page

**Comment by Jacalz** [comment]
Sorry for the long delay. I believe that this should be fixed with https://github.com/flathub/io.github.jacalz.rymdport/pull/25. I'll close the issue for now but feel free to reopen if it doesn't work (note that it will take a few hours for the new build to land in the stable channel of Flathub).

**Comment by qlyoung** [comment]
I am still encountering this issue on 3.6.0. I am not using the flatpak, I am using the AUR, which builds from source: https://aur.archlinux.org/packages/rymdport

**Comment by Jacalz** [comment]
Thinks for bringing this to my attention. I'll reopen this issue and look into it again. The intermediary zip file write is unfortunately part of how https://github.com/psanford/wormhole-william handles transfers so I might have to come up with a better solution there.

**Comment by Jacalz** [comment]
This is due to how the directory sends in the wormhole package are creating a temporary zip file when sending directories, see https://github.com/rymdport/wormhole/blob/4e36e05aff6c3cce139db9be3d973181e2b5a753/wormhole/send.go#L508. This file is then used when sending the transfer. This might be a bit tricky to fix in a good way given that the wormhole protocol requires the size to be known before initiating the send. I'm honestly not entirely sure how we can fix this without breaking that protocol :(

**Comment by qlyoung** [comment]
Would it be viable to allow configuring where the zip is created, so that it could be set to use a path not located on a ramdisk?On Jan 4, 2025, at 11:34 AM, Jacob Alzén ***@***.***> wrote:﻿
This is due to how the directory sends in the wormhole package are creating a temporary zip file when sending directories, see https://github.com/rymdport/wormhole/blob/4e36e05aff6c3cce139db9be3d973181e2b5a753/wormhole/send.go#L508. This file is then used when sending the transfer. This might be a bit tricky to fix in a good way given that the wormhole protocol requires the size to be known before initiating the send. I'm honestly not entirely sure how we can fix this without breaking that protocol :(

**Comment by Jacalz** [comment]
> Would it be viable to allow configuring where the zip is created, so that it could be set to use a path not located on a ramdisk?

Maybe. It solves the problem kind of but it also introduces other things do consider:

- Likely will be problematic for Flatpak apps when running inside a sandbox.
- Users would have to manually change this and know that changing temporary directly allows them to send larger files.

The best option would be to have some kind of streaming protocol for doing the transfers. That would mean finding something else than magic wormhole (limits compatibility with other clients).

**Comment by qlyoung** [comment]
I think a config option would be an adequate workaround given the lift involved in switching the transfer protocol. "Perfect is the enemy of good"QuentinOn Jan 4, 2025, at 1:47 PM, Jacob Alzén ***@***.***> wrote:﻿

Would it be viable to allow configuring where the zip is created, so that it could be set to use a path not located on a ramdisk?

Maybe. It solves the problem kind of but it also introduces other things do consider:

Likely will be problematic for Flatpak apps when running inside a sandbox.
Users would have to manually change this and know that changing temporary directly allows them to send larger files.

The best option would be to have some kind of streaming protocol for doing the transfers. That would mean finding something else than magic wormhole (limits compatibility with other clients).

**Comment by Jacalz** [comment]
Yes and no. I'm not a fan of workarounds and it would not fit well into the Flatpak app once I lower the drop permissions and use desktop portals. I intend to fix the reviving side by simply adding an option to not extract he zip file but I'll think more about this.

**Comment by rostebafyu** [comment]
I had been considering opening a ticket to add support for an environments var/config/arg/etc under the upstream WHW project per Jacalz's previous comment regarding the issue being due to `send.go`'s `makeTmpZip` function blindly using the /tmp ... but actually looking it over some more, I saw that it just calls golang's [CreateTemp](https://pkg.go.dev/os#CreateTemp) which after reading the doc, I saw says that:

> If dir is the empty string, CreateTemp uses the default directory for temporary files, as returned by TempDir. 

In turn, golang's [TempDir](https://pkg.go.dev/os#TempDir) function's doc says:

> TempDir returns the default directory to use for temporary files.
>
> On Unix systems, it returns $TMPDIR if non-empty, else /tmp. On Windows, it uses GetTempPath, returning the first non-empty value from %TMP%, %TEMP%, %USERPROFILE%, or the Windows directory. On Plan 9, it returns /tmp.
>
> The directory is neither guaranteed to exist nor have accessible permissions. 

So while I have no opinion on the best approach for solving this via code...

---

**Bottom line: I realized that if a user wants the CURRENT version of Rymdport to NOT use `/tmp` (e.g. bc it's a RAM drive and will run out of space for large files), then the work-around is simple: just set `TMPDIR` to the location that you want Rymdport to use instead.**

In my testing, I found that *both* parties need to implement the change, unless the person receiving just so happens to have the correct amount of RAM needed to receive whatever file you are sending.

---

Basically, decide on a location mounted on disk-based storage (SSD / hard-drive / etc), make sure you have correct permissions, and just map `TMPDIR` there. In the examples below, I am assuming that you are on Linux and using the flatpak version. While I haven't tested building a native version from source or on other platforms, I assume simply setting an environment variable there should also work. I picked the location `$HOME/.local/share/rymdport` (e.g. `/home/YOURUSERNAME/.local/share/rymdport`) but pretty much anything should work.


#### How to set it up from a terminal:

```bash
    d="$HOME/.local/share/rymdport";
    mkdir -p "$d";
    chmod 770 "$d";
    flatpak override --user io.github.jacalz.rymdport --filesystem="$d;
    flatpak override --user io.github.jacalz.rymdport --env=TMPDIR="$d";
```

**OR**

#### How to set the same thing graphically from Flatseal:

1. Make sure you have [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal) and launch it
2. Select Rymdport on the left-side pane
3. On the right-side, scroll down to the "**Filesystem**" section and in the last sub-section of that ("**Other file**"), click the "+" button to add a new folder definition. Then add whatever custom path you want.
4. Scroll down to the "**Environment**" section and click the `+` button then add the following: `TMPDIR=/your/custom/path/here`

**OR**

#### Probably how to do the same thing for native linux builds (UNTESTED)

should just be able to launch it from the terminal with the environment variable override on the same line, like so:

    TMPDIR="$HOME/.local/share/rymdport" rymdport

Or, if you want to make it work with your `.desktop` launchers, you can create a wrapper script, e.g.

```bash
    mkdir -p ~/.local/bin
    touch ~/.local/bin/rymdport-wrapper.sh
    chmod 770 ~/.local/bin/rymdport-wrapper.sh
```

with the wrapper script containing something like:

```bash
   #!/usr/bin/env bash
   TMPDIR="$HOME/.local/share/rymdport" rymdport
```

then just update your `.desktop` launcher file to use\*:

    Exec=/home/YOURUSERNAME/.local/bin/rymdport-wrapper.sh"

\* remember that `.desktop` files are not capable of expanding bash/zsh/fish/etc variables like `$HOME` or `~` without additional workarounds, hence the need to actually type out the fully resolved path.

Hopefully, all that is helpful to some other Rymdport enjoyers out there.

**Comment by Jacalz** [comment]
Thanks for the thorough write up. I have already forked the wormhole backend into https://github.com/rymdport/wormhole so there is absolutely room for fixing the source issue there, if possible in a clean way. Like I said, the wormhole protocol requires that we know the size before sending so we can stream the zip file creation. If anyone is interested in having a look at fixing it, I would appreciate it greatly.

My plan is to introduce a setting in the next release to allow revived directories to not be extracted and make that default (as it fits in well with sandbox-safe file save dialogs in Flatpak). That should solve the second part of the problem.
